version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc@123 
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: abc@123
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql